### ISSUE TITLE
TypeError: Unknown file extension ".ts"

### ISSUE THREAD

**Issue by vedran77** [YuCarl77/omp-node-ts#15]
Node version: 16.20.0

I executed 
`pnpm create @infernus/app`,
`cd testp`
`pnpm run dev`

and this happens, I also tried with git clone ..., same result

![image](https://github.com/dockfries/infernus-starter/assets/94656982/269d4e48-3dca-4f50-bcdc-f2de0d453941)

**Comment by dockfries** [comment]
Change the file name of `rollup.config.ts` to `rollup.config.mjs`	, this should solve the problem, although it is not clear what happened to `rollup`.

In addition, I just updated `package.json` and `tsconfig.json`, upgraded the dependencies, and you can replace the local files if necessary, and then `pnpm install` again.

**Comment by vedran77** [comment]
Thank you, I had another issue this time
![image](https://github.com/dockfries/infernus-starter/assets/94656982/527bc2b3-dd82-4236-baaf-70a7d45f0f0f)

I can see that you added "type": "module", in pacakge.json, are you sure about that? I removed it from my package.json and it works. Also I'm not sure does `samp-node` works when type is set to module ?

**Comment by dockfries** [comment]
You're right. type should not be set to module, although the generated js is the specification of cjs, but node still runs the file according to the setting of package.json.
